import { useEffect, useRef, useState } from "react";
import "../../styles/components/StudentPhotoCropper.css";
export default function StudentPhotoCropper({source,onCancel,onSave}){
 const canvas=useRef(null),img=useRef(null),drag=useRef(null); const [ready,setReady]=useState(false),[zoom,setZoom]=useState(1),[pos,setPos]=useState({x:0,y:0}); const S=320;
 const met=(z=zoom)=>{if(!img.current)return null;const b=Math.max(S/img.current.naturalWidth,S/img.current.naturalHeight),s=b*z,w=img.current.naturalWidth*s,h=img.current.naturalHeight*s;return{w,h,minX:S-w,minY:S-h}};
 const clamp=(p,z=zoom)=>{const m=met(z);return m?{x:Math.min(0,Math.max(m.minX,p.x)),y:Math.min(0,Math.max(m.minY,p.y))}:p};
 useEffect(()=>{const i=new Image();i.onload=()=>{img.current=i;const b=Math.max(S/i.naturalWidth,S/i.naturalHeight),w=i.naturalWidth*b,h=i.naturalHeight*b;setPos({x:(S-w)/2,y:(S-h)/2});setReady(true)};i.src=source},[source]);
 useEffect(()=>{const c=canvas.current,i=img.current;if(!ready||!c||!i)return;const b=Math.max(S/i.naturalWidth,S/i.naturalHeight),s=b*zoom,w=i.naturalWidth*s,h=i.naturalHeight*s,x=c.getContext("2d");x.clearRect(0,0,S,S);x.drawImage(i,pos.x,pos.y,w,h)},[ready,zoom,pos]);
 const save=()=>{const m=met(),o=document.createElement("canvas");o.width=o.height=512;const x=o.getContext("2d"),r=512/S;x.drawImage(img.current,pos.x*r,pos.y*r,m.w*r,m.h*r);onSave(o.toDataURL("image/jpeg",.9))};
 return <div className="student-crop-backdrop"><section className="student-crop-modal"><div className="student-crop-head"><div><h2>Adjust profile photo</h2><p>Drag and zoom the image to choose what appears in your avatar.</p></div><button onClick={onCancel}>×</button></div><div className="student-crop-stage" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,p:pos}}} onPointerMove={e=>{if(drag.current){const d=drag.current;setPos(clamp({x:d.p.x+e.clientX-d.x,y:d.p.y+e.clientY-d.y}))}}} onPointerUp={()=>drag.current=null}><canvas ref={canvas} width={S} height={S}/><div className="student-crop-mask"/></div><label className="student-zoom"><span>Zoom</span><input type="range" min="1" max="3" step=".01" value={zoom} onChange={e=>{const z=+e.target.value;setZoom(z);setPos(p=>clamp(p,z))}}/><b>{Math.round(zoom*100)}%</b></label><div className="student-crop-actions"><button onClick={onCancel}>Cancel</button><button disabled={!ready} onClick={save}>Use Photo</button></div></section></div>
}
