const esc=(v='')=>String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

function printable(title,body){
 const w=window.open('','_blank','width=900,height=900');
 if(!w){alert('Please allow pop-ups so PulseUp can open the printable document.');return;}
 w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
 @page{size:A4;margin:18mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172033;margin:0;font-size:13px;line-height:1.5}
 .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #0b3c66;padding-bottom:15px;margin-bottom:24px}.brand{font-size:25px;font-weight:800;color:#0b3c66}.muted{color:#687789}.doc-title{text-align:right}.doc-title h1{margin:0;color:#0b3c66;font-size:22px}.doc-title p{margin:4px 0}
 .section{margin:18px 0}.section h2{font-size:14px;color:#0b3c66;border-bottom:1px solid #dce3ea;padding-bottom:6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 24px}.field{padding:7px 0}.field span{display:block;color:#687789;font-size:11px}.field strong{display:block}.box{padding:12px;border:1px solid #dce3ea;border-radius:7px;white-space:pre-wrap}
 .doctor{margin-top:30px;padding-top:15px;border-top:1px solid #dce3ea}.signature{margin-top:38px;width:260px;border-top:1px solid #172033;padding-top:5px}.footer{margin-top:35px;padding-top:10px;border-top:1px solid #dce3ea;text-align:center;color:#687789;font-size:10px}
 .status{display:inline-block;padding:4px 9px;border-radius:12px;background:#eaf8ef;color:#18864b;font-weight:700}@media print{button{display:none!important}}
 </style></head><body>${body}<script>window.onload=()=>{window.print()}</script></body></html>`);
 w.document.close();
}

export function healthQuestPdf(q){
 printable(`Healthquest-${q.patientId}`,`
 <header class="head"><div><div class="brand">PulseUp</div><div class="muted">Campus Clinic</div></div><div class="doc-title"><h1>Healthquest Report</h1><p>Reference: HQ-${esc(q.id)}</p></div></header>
 <section class="section"><h2>Patient Information</h2><div class="grid"><div class="field"><span>Patient Name</span><strong>${esc(q.patient)}</strong></div><div class="field"><span>Patient ID</span><strong>${esc(q.patientId)}</strong></div><div class="field"><span>Healthquest Type</span><strong>${esc(q.type)}</strong></div><div class="field"><span>Date</span><strong>${esc(q.date)}</strong></div><div class="field"><span>Status</span><strong>${esc(q.status)}</strong></div></div></section>
 <section class="section"><h2>Healthquest Record</h2><div class="box">This document records the PulseUp healthquest shown in the clinic administration system. Additional questionnaire responses can be populated here when the Healthquest API/data model is connected.</div></section>
 <div class="footer">Generated by PulseUp Campus Clinic • ${new Date().toLocaleDateString()}</div>`);
}

export function sickNotePdf(n,doctor){
 const ref=`SN-${String(n.id).slice(-8)}`;
 printable(`Sick-Note-${n.patientId}-${ref}`,`
 <header class="head"><div><div class="brand">PulseUp</div><div class="muted">Campus Clinic</div></div><div class="doc-title"><h1>Medical Sick Note</h1><p>Reference: ${esc(ref)}</p><span class="status">${esc(n.status)}</span></div></header>
 <section class="section"><h2>Patient Information</h2><div class="grid"><div class="field"><span>Patient Name</span><strong>${esc(n.patient)}</strong></div><div class="field"><span>Patient ID</span><strong>${esc(n.patientId)}</strong></div><div class="field"><span>Medical Reason</span><strong>${esc(n.reason)}</strong></div><div class="field"><span>Recommended Recovery / Leave</span><strong>${esc(n.duration)} ${n.duration===1?'Day':'Days'}</strong></div><div class="field"><span>Date Issued</span><strong>${new Date().toLocaleDateString()}</strong></div></div></section>
 <section class="section"><h2>Doctor's Notes</h2><div class="box">${esc(n.notes)}</div></section>
 <section class="doctor"><h2>Issuing Medical Practitioner</h2><div class="grid"><div class="field"><span>Doctor</span><strong>${esc(doctor.name)}</strong></div><div class="field"><span>Staff / Practitioner ID</span><strong>${esc(doctor.staff||'Not provided')}</strong></div><div class="field"><span>Qualification</span><strong>${esc(doctor.qualification||'Not provided')}</strong></div><div class="field"><span>Position</span><strong>${esc(doctor.position||'Doctor')}</strong></div><div class="field"><span>Institution / Clinic</span><strong>${esc(doctor.institution||'PulseUp Campus Clinic')}</strong></div><div class="field"><span>Email</span><strong>${esc(doctor.email||'Not provided')}</strong></div><div class="field"><span>Phone</span><strong>${esc(doctor.phone||'Not provided')}</strong></div></div><div class="signature">Doctor / Authorized Signature</div></section>
 <div class="footer">Generated by PulseUp Campus Clinic. This printable copy reflects the approved record stored in the application.</div>`);
}
