import { useMemo, useState } from "react";
import { sickNotePdf } from "../../utils/adminDocumentPdf";
import "../../styles/pages/AdminSickNotes.css";

const seed=[
 {id:1,patient:"John Doe",patientId:"ST20301",reason:"Flu & Fever",duration:3,status:"Approved",notes:"Patient diagnosed with flu symptoms and advised bed rest for 3 days."},
 {id:2,patient:"Sarah Smith",patientId:"ST20302",reason:"Back Pain",duration:5,status:"Pending",notes:"Patient experiencing lower back pain and requires physiotherapy assessment."}
];
const defaultDoctor={name:"Dr Inga Plati",staff:"12345",phone:"071 234 5678",email:"inga@email.com",qualification:"PhD",institution:"UCT",position:"Doctor"};
function currentDoctor(){try{return {...defaultDoctor,...JSON.parse(localStorage.getItem("pulseupAdminProfile")||"{}")}}catch{return defaultDoctor}}

export default function AdminSickNotes(){
 const [notes,setNotes]=useState(seed),[createOpen,setCreateOpen]=useState(false),[selected,setSelected]=useState(null);
 const [form,setForm]=useState({patient:"",patientId:"",reason:"",duration:"",notes:""});
 const total=notes.length,approved=useMemo(()=>notes.filter(n=>n.status==="Approved").length,[notes]),pending=useMemo(()=>notes.filter(n=>n.status==="Pending").length,[notes]);
 const create=e=>{e.preventDefault();const days=Number(form.duration);if(!form.patient.trim()||!form.patientId.trim()||!form.reason.trim()||!form.notes.trim()||!Number.isInteger(days)||days<1){alert("Please complete all fields and enter a valid duration.");return}setNotes(n=>[{id:Date.now(),...form,duration:days,status:"Pending"},...n]);setForm({patient:"",patientId:"",reason:"",duration:"",notes:""});setCreateOpen(false);alert("Sick note created successfully.")};
 const setStatus=(id,status)=>{setNotes(list=>list.map(n=>n.id===id?{...n,status}:n));setSelected(s=>s?.id===id?{...s,status}:s)};
 const download=n=>{if(n.status!=="Approved"){alert("Only approved sick notes can be downloaded as official printable documents.");return}sickNotePdf(n,currentDoctor())};
 return <div className="admin-sicknotes-page">
  <div className="asn-intro"><div><h2>Sick Notes</h2><p>Manage patient medical leave documents</p></div><button onClick={()=>setCreateOpen(true)}>+ Create Sick Note</button></div>
  <section className="asn-stats"><article className="total"><span>Total Sick Notes</span><strong>{total}</strong></article><article className="approved"><span>Approved</span><strong>{approved}</strong></article><article className="pending"><span>Pending</span><strong>{pending}</strong></article></section>
  <section className="asn-table-panel"><h3>Recent Sick Notes</h3><div className="asn-table-scroll"><table><thead><tr><th>Patient</th><th>Reason</th><th>Duration</th><th>Status</th><th>Action</th></tr></thead><tbody>{notes.map(n=><tr key={n.id}><td>{n.patient}</td><td>{n.reason}</td><td>{n.duration} {n.duration===1?"Day":"Days"}</td><td><span className={`asn-status ${n.status.toLowerCase()}`}>{n.status}</span></td><td><div className="asn-row-actions"><button className="asn-view" onClick={()=>setSelected(n)}>View</button>{n.status==="Approved"&&<button className="asn-download" onClick={()=>download(n)}>Download PDF</button>}</div></td></tr>)}</tbody></table></div></section>
  {createOpen&&<div className="admin-modal-backdrop" onMouseDown={()=>setCreateOpen(false)}><section className="asn-modal wide" onMouseDown={e=>e.stopPropagation()}><div className="admin-modal-head"><h2>Create Sick Note</h2><button onClick={()=>setCreateOpen(false)}>×</button></div><form onSubmit={create}><div className="asn-form-grid"><label>Patient Name<input value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})}/></label><label>Patient ID<input value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})}/></label><label>Reason<input value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><label>Duration (Days)<input type="number" min="1" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><label className="asn-notes-field">Doctor Notes<textarea rows="4" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="asn-actions"><button type="button" onClick={()=>setCreateOpen(false)}>Cancel</button><button type="submit">Save Sick Note</button></div></form></section></div>}
  {selected&&<div className="admin-modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="asn-modal wide" onMouseDown={e=>e.stopPropagation()}><div className="admin-modal-head"><h2>Sick Note Information</h2><button onClick={()=>setSelected(null)}>×</button></div><div className="asn-details-grid"><label>Patient Name<input readOnly value={selected.patient}/></label><label>Sick Note Status<input readOnly value={selected.status}/></label><label>Medical Reason<input readOnly value={selected.reason}/></label><label>Recovery Duration<input readOnly value={`${selected.duration} ${selected.duration===1?"Day":"Days"}`}/></label><label className="asn-notes-field">Doctor Notes<textarea rows="4" readOnly value={selected.notes}/></label></div>{selected.status==="Pending"&&<div className="asn-review-actions"><button onClick={()=>setStatus(selected.id,"Rejected")}>Reject</button><button onClick={()=>setStatus(selected.id,"Approved")}>Approve</button></div>}<div className="asn-detail-actions">{selected.status==="Approved"&&<button className="asn-download" onClick={()=>download(selected)}>Download PDF</button>}<button className="asn-close" onClick={()=>setSelected(null)}>Close</button></div></section></div>}
 </div>
}
